apiVersion: v1
kind: Service
metadata:
  name: cursus-lms-api-service
spec:
  selector:
    app: cursus-lms-api
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: grpc-port
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
